version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/app:/app

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend/app:/app
    environment:
      DB_HOST: mysql
      DB_NAME: sauna_booking_system
      DB_USER: sauna_user
      DB_PASSWORD: sauna_password
      DB_CHARSET: utf8mb4
      JWT_SECRET: your_jwt_secret_key_change_in_production

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: sauna_user
      MYSQL_PASSWORD: sauna_password
      MYSQL_DATABASE: sauna_booking_system
    volumes:
      - mysqldata:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: sauna_user
      PMA_PASSWORD: sauna_password
    ports:
      - 8080:80
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

volumes:
  mysqldata: {}